diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.DiaryListView.as_view(), name='diary_list'),
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),
    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment_create'),
    path('diary-create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(), name='diary_update'),
    path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('', include('diary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = 'CustomUser'

diary/models.py
from django.db import models

# Create your models here.
class Diary(models.Model):
    author = models.CharField(verbose_name='投稿者', max_length=20)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='内容', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真１', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真２', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真３', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
        return self.title

class Comment(models.Model):
    text = models.TextField('本文')
    author = models.CharField(verbose_name='コメント者', max_length=20,default='匿名')
    target = models.ForeignKey(Diary, on_delete=models.CASCADE, verbose_name='どの記事へのコメントか')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)

    def __str__(self):
        return self.text[:20]

diary/forms.py
from .models import Diary, Comment
from django import forms

class DiaryCreateForm(forms.ModelForm):

    class Meta:
        model = Diary
        fields = ('author','title', 'content', 'photo1', 'photo2', 'photo3',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text','author')
        widgets = {
            'text':forms.Textarea(attrs={'class': 'textarea form-control'}),
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from .models import Diary, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import DiaryCreateForm, CommentCreateForm
from django.urls import reverse_lazy
from django.db.models import Q

# Create your views here.
class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    ordering = ['-created_at']
    template_name = 'diary/diary_list.html'
    paginate_by = 5

    def get_queryset(self):
        q_word = self.request.GET.get('query')
        if q_word:
            diary_list = Diary.objects.filter(
                Q(author__icontains=q_word) | Q(title__icontains=q_word) | Q(content__icontains=q_word))
        else:
            diary_list = Diary.objects.all().order_by('-created_at')
        return diary_list

class DiaryDetailView(LoginRequiredMixin,generic.DetailView):
    model = Diary
    template_name = 'diary/diary_detail.html'

class CommentCreateView(LoginRequiredMixin,generic.CreateView):
    model = Comment
    template_name = 'diary/comment_create.html'
    form_class = CommentCreateForm

    def form_valid(self, form):
        diary_pk = self.kwargs['pk']
        diary = get_object_or_404(Diary,pk=diary_pk)
        comment = form.save(commit=False)
        comment.target = diary
        comment.save()
        return redirect('diary:diary_detail',pk=diary_pk)

class DiaryCreateView(LoginRequiredMixin,generic.CreateView):
    model = Diary
    template_name = 'diary/diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary_list')


class DiaryUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Diary
    template_name = 'diary/diary_update.html'
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('diary:diary_detail',kwargs={'pk':self.kwargs['pk']})

class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary/diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-S55CPEY9F0"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-S55CPEY9F0');
        </script>

        {% block head %}{% endblock %}
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'diary:diary_list' %}">Private Diary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'diary:diary_list' %}">日記一覧</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}

        <!-- Footer-->
        <div class="my-div-style">
        <footer class="py-5 bg-black my-footer-style">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright Shun Katakura 2022</p></div>
        </footer>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/diary/comment_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}コメント追加{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">コメント作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/diary/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/diary/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>  <!--1-->
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/diary/diary_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}日記の詳細{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.title }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>
            <div class="col-9">
                {{ object.content | linebreaksbr | urlize }}
            </div>
        </div>

        <hr>

         <div class="row">
            <div class="col-3">
                <strong>写真</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                    <img src="{{ object.photo1.url }}" width="200" height="200" />
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo2 %}
                    <img src="{{ object.photo2.url }}" width="200" height="200" />
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo3 %}
                    <img src="{{ object.photo3.url }}" width="200" height="200" />
                {% endif %}
            </div>
        </div>


        <hr>


        <div class="row">
            <div class="col-3">
                <strong>投稿者</strong>
            </div>
            <div class="col-9">
                {{ object.author }}
            </div>
        </div>

        <hr>


        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>
　　　　　　
        <a class="btn btn-info mt-5 mb-3" href="{% url 'diary:comment_create' object.pk %}">コメントする</a>
        <a class="btn btn-primary mt-5 mb-3" href="{% url 'diary:diary_list' %}">戻る</a>
        <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' object.pk %}">編集</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' object.pk %}">削除</a>

        <section class="section">
            {% for comment in object.comment_set.all %}
            <div class="box">
                {{ comment.text | linebreaks | urlize }} - {{ comment.author }}より - {{ comment.created_at }}
            </div>

            <hr>
            {% endfor %}
        </section>
    </div>
</div>
{% endblock %}

templates/diary/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block header %}

    <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>日記一覧</h1>
                    <span class="subheading">日記一覧</span>
                </div>
            </div>
        </div>
    </div>
    </header>

{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5">

    <div class="row gx-4 gx-lg-5 justify-content-center">

        <div class="col-md-10 col-lg-8 col-xl-7">

            <div class="d-flex flex-row mb-3 justify-content-between">
                <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>
                <div class="float-right">
                    <form method="GET">
                        <input name="query" value="{{ request.GET.query }}" type="text">
                        <button class="btn btn-info" type="submit">検索する</button>
                    </form>
                </div>
            </div>

            <!-- Post preview-->
            <hr>
            {% for diary in diary_list %}
            <div class="post-preview">
                <a href="{% url 'diary:diary_detail' diary.pk %}">
                    <h2 class="post-title">{{ diary.title }}</h2>
                    <h3 class="post-subtitle">{{ diary.content | truncatechars:20 }}</h3>
                </a>
                <p class="post-meta">Posted by {{ diary.author }}, {{ diary.created_at }}</p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% empty %}
            <p>雑記がありません。</p>
            {% endfor %}

            <!-- Pager-->
            {% if is_paginated %}
                <ul class="pagination">
                    <!-- 前ページへのリンク -->
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    <!-- ページ数表示 -->
                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!-- 次ページへのリンク -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}

        </div>

    </div>
</div>
{% endblock %}

templates/diary/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}雑記編集{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}